version: '3'

tasks:
  deps:
    desc: Install development dependencies
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  build:
    desc: Build all services
    cmds:
      - go build -o bin/service-a ./services/service-a/cmd
      - go build -o bin/service-b ./services/service-b/cmd

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/ 